// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyZW9YEoSyGLxibEevhyHbRVk9N_8aOc',
    appId: '1:662676273278:web:5d9f7a312cda16c5c9402f',
    messagingSenderId: '662676273278',
    projectId: 'gowrish-test',
    authDomain: 'gowrish-test.firebaseapp.com',
    databaseURL: 'https://gowrish-test-default-rtdb.firebaseio.com',
    storageBucket: 'gowrish-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN00d6eLa2EUDXuySjxuRf-PVi3fYAIz8',
    appId: '1:662676273278:android:1c73baa01e25fffcc9402f',
    messagingSenderId: '662676273278',
    projectId: 'gowrish-test',
    databaseURL: 'https://gowrish-test-default-rtdb.firebaseio.com',
    storageBucket: 'gowrish-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Y_KPBd2_N17ahrN2r63XxZU1_5NdAuE',
    appId: '1:662676273278:ios:044876ab5bbf5f77c9402f',
    messagingSenderId: '662676273278',
    projectId: 'gowrish-test',
    databaseURL: 'https://gowrish-test-default-rtdb.firebaseio.com',
    storageBucket: 'gowrish-test.appspot.com',
    iosBundleId: 'com.example.bot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Y_KPBd2_N17ahrN2r63XxZU1_5NdAuE',
    appId: '1:662676273278:ios:044876ab5bbf5f77c9402f',
    messagingSenderId: '662676273278',
    projectId: 'gowrish-test',
    databaseURL: 'https://gowrish-test-default-rtdb.firebaseio.com',
    storageBucket: 'gowrish-test.appspot.com',
    iosBundleId: 'com.example.bot',
  );
}
